services:
  db: 
    image: 'mysql:latest'
    restart: always
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      # - MYSQL_ROOT_HOST='172.18.0.1'
      - MYSQL_ROOT_PASSWORD='root'
    ports:
      - '3306:3306'
    container_name: COSMO-GROUP-DB
  api:
    depends_on:
      - db
    ports:
      - 5000:5000
    container_name: COSMO-GROUP-API
    build: .
    restart: unless-stopped